### ISSUE TITLE
Setting contentType = text/calendar fails to add alternate section

### ISSUE THREAD

**Issue by soitgoes** [andris9/mailcomposer#48]
I can get an alternate section to add to the message when using text/plain but as soon as I change it to text/calendar then it doesn't render.

This demonstrates the problem.

var mailer = require('nodemailer');
var smtpPool = require('nodemailer-smtp-pool');
var alternatives = [{content:"contents of alternative", contentEncoding:"7bit", contentType:"text/calendar"}];
var smtpTransport = mailer.createTransport(smtpPool(config));

var message = {
      from: "someguy@somewhere.com",
      to: "martin.murphy@whiteboard-it.com",
      subject: "Hello World",
      html: "html",
      alternatives:alternatives,
    };
   
smtpTransport.sendMail(message);

**Comment by andris9** [comment]
I'm not sure what's the issue, the script seems to be working fine. It generates a *multipart/alternative* block with tho child nodes *text/html* and *text/calendar*

```
Content-Type: multipart/alternative;
 boundary="----sinikael-?=_1-14302027488570.05876986007206142"
From: someguy@somewhere.com
To: martin.murphy@whiteboard-it.com
Subject: Hello World

------sinikael-?=_1-14302027488570.05876986007206142
Content-Type: text/html
Content-Transfer-Encoding: 7bit

html
------sinikael-?=_1-14302027488570.05876986007206142
Content-Type: text/calendar
Content-Transfer-Encoding: 7bit

contents of alternative
------sinikael-?=_1-14302027488570.05876986007206142--
```

And when opening such message my email client displays a calendar attachment:

![](https://cldup.com/Jk4iWxgPqF.png)

So everything seems fine or do you expect something else?

**Comment by soitgoes** [comment]
Hmm.  Maybe mandrill is parsing it out for some reason.  I'll know more
shortly after I test with vanilla smtp

On Tue, Apr 28, 2015 at 1:37 AM, Andris Reinman <notifications@github.com>
wrote:

> I'm not sure what's the issue, the script seems to be working fine. It
> generates a *multipart/alternative* block with tho child nodes *text/html*
> and *text/calendar*
>
> Content-Type: multipart/alternative;
>  boundary="----sinikael-?=_1-14302027488570.05876986007206142"
> From: someguy@somewhere.com
> To: martin.murphy@whiteboard-it.com
> Subject: Hello World
>
> ------sinikael-?=_1-14302027488570.05876986007206142
> Content-Type: text/html
> Content-Transfer-Encoding: 7bit
>
> html
> ------sinikael-?=_1-14302027488570.05876986007206142
> Content-Type: text/calendar
> Content-Transfer-Encoding: 7bit
>
> contents of alternative
> ------sinikael-?=_1-14302027488570.05876986007206142--
>
> And when opening such message my email client displays a calendar
> attachment:
>
>
> <https://camo.githubusercontent.com/d0dc70a17a5e4b7fd988dd78f96df0c48537ca8a/68747470733a2f2f636c6475702e636f6d2f4a6b34695778675071462e706e67>
>
> So everything seems fine or do you expect something else?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/andris9/mailcomposer/issues/48#issuecomment-96946270>.
>



-- 
Martin Murphy
Whiteboard-IT
http://whiteboard-it.com
w: (205) 588-7102

**Comment by soitgoes** [comment]
mandrillapp is parsing out this multipart boundary for some rediculous reason.  I confirmed it's working.  Sorry to bug you.
