### ISSUE TITLE
Questions about new version 1.0.0

### ISSUE THREAD

**Issue by Sjonnie2nd** [andris9/mailcomposer#54]
Hello Andris,

Today I upgraded to 1.0.0 and ran into some issues. Perhaps mentioning them here will help others too.

- Both mailcomposer and mailparser used "fileName" for an attachment. (with a capital N). Now mailcomposer uses "filename". This gets a bit tricky when an existing email is parsed, edited and composed again.
(Note: the other way arround: The difference between mailparsers "content" and mailcomposers "contents" is now gone :+1: )

- Is the option escapeSMTP gone? (and not needed anymore?)

- Is the option forceEmbeddedImages gone? I liked that one.

Greetings, Ronald

**Comment by andris9** [comment]
*mailcomposer* is mainly used for generating messages with Nodemailer and Nodemailer does not need these features anymore and the API is also slightly different (like the mentioned *filename* example). If you want to keep using the old *mailcomposer* API, do not upgrade from the v0.2.12 version.
