### ISSUE TITLE
Issues with .build

### ISSUE THREAD

**Issue by frenchy75** [andris9/mailcomposer#58]
Hi
I have a 'build method doesn't exist' issue. Can you update your doc ?
I tried to use:
"
var mail = mailcomposer({from: '...', ...});
mail.build(function(err, message){
    process.stdout.write(message);
});
"

Thanks for your help :)

**Comment by andris9** [comment]
build method behaves like documented. This is how you'd use it:

```javascript
var mailcomposer = require('mailcomposer');
var mail = mailcomposer(data);
mail.build(function(err, message){
     console.log(err || message);
});
```

**Comment by frenchy75** [comment]
My bad, I based my code on http://www.dominikschmidt.net/2015/08/sending-emails-with-attachement-for-new-s3-objects/ and he used "var MailComposer = require('mailcomposer').MailComposer"...
It works now!

One more issue for me (probably not a bug): I am trying to send an email with an mp3 attachment coming from S3.
My code:

```JavaScript
s3.getObject(params, function(err, data) {
  if (err) {
  } else {
    var mailOptions = {
      from: 'xxxx',
      to: 'vxxxx',
      subject: 'xxxx',
      body: 's3://' + bucket + '/' + key,
      attachments: [{
        filename: 'voicemail.mp3',
        contents: data.Body,
        contentType: 'audio/mpeg',
        encoding: 'binary',
        //cid: key,
        }]
    };
    
    var mailcomposer = MailComposer(mailOptions);
    mailcomposer.build(function(err, messageSource) {
      if (err) {
        } else {
            ses.sendRawEmail({RawMessage: {Data: messageSource}}, function(err, data) {
              if(err) {
              } else {
                  context.done(null, data);
              }
            });
        }
    });
  }
});
```
data.Body is a Buffer but it doesn't seems to get transformed well
I get the email fine, with the proper attachment name and type but with a Zero byte file....

Thanks again for the great piece of software and the quick support!
