### ISSUE TITLE
`bcc` field doesn't appear since update to 1.x/2.x

### ISSUE THREAD

**Issue by fiznool** [andris9/mailcomposer#59]
We are using mailcomposer 0.2 to create a mail message, which we can then send via the GMail node API to add a new draft.

In 0.2, we had the option `keepBcc` which meant that the `bcc` field in the draft could be populated.

Since updating to 2.x, this no longer works. Is there another configuration setting somewhere which will provide the desired behaviour?

**Comment by andris9** [comment]
keepBcc can be used like this:

```javascript
var mailcomposer = require('mailcomposer');
var mail = mailcomposer({bcc: 'test@example.com'});
mail.keepBcc = true;
mail.createReadStream().pipe(process.stdout);
```

Example output for such a snipped would be like this:

```
Content-Type: text/plain
Bcc: test@example.com
Date: Wed, 18 Nov 2015 19:06:41 +0000
Message-Id: <1447873601449-216fa169-e7cc7f19-6ada8c4e@localhost>
MIME-Version: 1.0

```

**Comment by fiznool** [comment]
Great, thanks!
